---
- include: deps.yml
- name: Copy user-manager-db
  copy:
    src=user-manager-db
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Run npm install
  command: npm install
    chdir=/usr/local/src/user-manager-db
    creates=/usr/local/src/user-manager-db/node_modules
- name: Setup Database
  command: npm run setup -- --force
    chdir=/usr/local/src/user-manager-db
